language: swift
osx_image: xcode12
before_install:
  - "gem install cocoapods"
  - "pod install"
  - "pod repo update"
before_script: 
  - "./scripts/add-keys.sh"
after_script:
  - "./scripts/remove-key.sh"
script:
  - "./scripts/buildSilverMobSdk.sh <<< $'y\n'" 
  - "./scripts/testSilverMobSdk.sh"
  - "./scripts/testPrebidDemo.sh"
  # - "./scripts/swiftLint.sh"
