platform :ios, '10.0'

target 'TestPodspecModules' do
    use_frameworks!

    pod 'SilverMobSdkRendering'
    pod 'SilverMobSdkMoPubAdapters' 
    pod 'SilverMobSdkGAMEventHandlers'

    pod 'Google-Mobile-Ads-SDK'
    pod 'mopub-ios-sdk', '5.16.2'
end
